"""Trusted LD-D2 built-in operator package."""

from .contract import (
    MAX_SPATIAL_TOKENS,
    OPERATOR_ID,
    OPERATOR_VERSION,
    Algorithm,
    ArtisticMode,
    D2Context,
    D2ContractError,
    D2Controls,
    ProcessResult,
    Routing,
    Xs5Routing,
)
from .descriptor import get_descriptor, get_descriptor_schema
from .operator import process_slot
from .stream import (
    MAX_STREAM_GENERATION,
    D2DecodedSlot,
    D2DecodePump,
    D2Paused,
    D2ProcessedSlot,
    D2ResetBarrier,
    D2Source,
    D2Step,
    D2StreamEngine,
    D2StreamError,
    D2Transport,
)
from .trusted import (
    BuiltinOperatorRegistry,
    LoadedOperator,
    OperatorDescriptor,
    OperatorLoadError,
    builtin_registry,
    validate_descriptor,
)

__all__ = [
    "MAX_SPATIAL_TOKENS",
    "OPERATOR_ID",
    "OPERATOR_VERSION",
    "Algorithm",
    "ArtisticMode",
    "D2Context",
    "D2ContractError",
    "D2Controls",
    "D2DecodePump",
    "D2DecodedSlot",
    "D2Paused",
    "D2ProcessedSlot",
    "D2ResetBarrier",
    "D2Source",
    "D2Step",
    "D2StreamEngine",
    "D2StreamError",
    "D2Transport",
    "MAX_STREAM_GENERATION",
    "BuiltinOperatorRegistry",
    "LoadedOperator",
    "OperatorDescriptor",
    "OperatorLoadError",
    "ProcessResult",
    "Routing",
    "Xs5Routing",
    "get_descriptor",
    "get_descriptor_schema",
    "builtin_registry",
    "process_slot",
    "validate_descriptor",
]
