from collections.abc import Sequence
from typing import Final

BINDING_ABI_VERSION: Final[str]
__version__: Final[str]

class RingError(Exception):
    code: str
    detail: str

class WindowsRgbRingProducer:
    @staticmethod
    def open(
        mapping_handle: int,
        frames_ready_event_handle: int,
        mapping_bytes: int,
        expected_generation: int,
        expected_width: int,
        expected_height: int,
    ) -> WindowsRgbRingProducer: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def row_stride(self) -> int: ...
    @property
    def mapping_bytes(self) -> int: ...
    @property
    def generation(self) -> int: ...
    @property
    def write_sequence(self) -> int: ...
    @property
    def read_sequence(self) -> int: ...
    @property
    def occupancy(self) -> int: ...
    @property
    def available_capacity(self) -> int: ...
    def can_publish(self, frame_count: int) -> bool: ...
    def publish_cycle(self, frames: Sequence[bytes], timestamp_ns: int) -> tuple[int, int]: ...
    def set_generation(self, new_generation: int) -> None: ...
    def close(self) -> None: ...
